version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: stage
      POSTGRES_PASSWORD: stage
      POSTGRES_DB: db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5433:5432"